### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by jacobmedley** [zaus/forms-3rdparty-dynamicfields#11]
We are using 3rd Party Integration with GravityForms. Most of the time it works fine, but we occasionally get an error “cURL error 28” (raw response below). I searched the forum for this error but did not find anything and made inquires to GF and our Server Support Team.

- GravityForms basically said “Not It!”.

- Our server team wanted to know if this plugin processes anything on another server? If so our fire wall might be causing an issue with it?

- Is this a server, GF or 3rdParty Integration issue?

**_What other avenues can I explore to resolve this?_**

`
Array
( [safe_message] => error object
    [object] => WP_Error Object (
            [errors] => Array (
                    [http_request_failed] => Array (
                            [0] => cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received )
 )
 [error_data] => Array (
                ) 
) )
`

**Comment by zaus** [comment]
It's a server issue -- my plugin is reporting that after sending the GF submission to your 3rdparty endpoint (presumably the "server" we're talking about) that server is taking too long to accept whatever you sent.  As you indicated, it happens occasionally which is probably to be expected (as computers are sometimes slow for various reasons, high traffic, time of day conflicting with update tasks, etc).  Since it only happens occasionally I wouldn't think it'd be a firewall issue (or it would happen all the time).  Most likely it's occurring during a database backup or server maintenance window, which causes everything to slow down.

You could:
* increase the timeout setting in my plugin, so WP will wait longer for your server to finish whatever it's doing; this runs the risk of letting your user sit there _forever_ (or however long you put) when this happens, and if you have a lot of people doing this at the same time you potentially lock up your website when they're all sitting around too long
* check your server logs/monitoring to see what's happening at the time -- are you seeing a spike in number of requests, leading to CPU or memory spikes?  Do you have scheduled tasks running at the same time, like Windows Updates or backups?
* increase the "size" of your server (i.e. beefier CPU or more memory, depending on what's causing it to slow down)

**Comment by jacobmedley** [comment]
Thank You.
